receivers:
 otlp:
   protocols:
     http:
     grpc:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 500
  prometheusremotewrite: # the PRW exporter, to ingest metrics to backend
    endpoint: 'http://host.docker.internal:9090/api/v1/write'
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheusremotewrite]
  telemetry:
    logs:
      level: "debug"
