global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['collector:9090']

  - job_name: collector
    static_configs:
      - targets: ['collector:4317']

  - job_name: server
    static_configs:
      - targets: ['collector:8888']
